/* Generated by Yosys 0.62+95 (git sha1 53d8eb43f, clang++ 18.1.8 -fPIC -O3) */

(* hdlname = "counter" *)
(* top =  1  *)
(* src = "counter.v:1.1-11.10" *)
module counter(clk, rst, en, \count[0] , \count[1] );
  (* src = "counter.v:2.9-2.12" *)
  input clk;
  wire clk;
  (* src = "counter.v:3.9-3.12" *)
  input rst;
  wire rst;
  (* src = "counter.v:4.9-4.11" *)
  input en;
  wire en;
  (* src = "counter.v:5.20-5.25" *)
  output \count[0] ;
  wire \count[0] ;
  (* src = "counter.v:5.20-5.25" *)
  output \count[1] ;
  wire \count[1] ;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  NOT _11_ (
    .A(\count[1] ),
    .Y(_08_)
  );
  NOT _12_ (
    .A(rst),
    .Y(_09_)
  );
  NAND _13_ (
    .A(en),
    .B(\count[0] ),
    .Y(_10_)
  );
  NOR _14_ (
    .A(en),
    .B(\count[0] ),
    .Y(_02_)
  );
  NOR _15_ (
    .A(rst),
    .B(_02_),
    .Y(_03_)
  );
  NAND _16_ (
    .A(_10_),
    .B(_03_),
    .Y(_04_)
  );
  NOT _17_ (
    .A(_04_),
    .Y(_00_)
  );
  NOR _18_ (
    .A(_08_),
    .B(_10_),
    .Y(_05_)
  );
  NAND _19_ (
    .A(_08_),
    .B(_10_),
    .Y(_06_)
  );
  NAND _20_ (
    .A(_09_),
    .B(_06_),
    .Y(_07_)
  );
  NOR _21_ (
    .A(_05_),
    .B(_07_),
    .Y(_01_)
  );
  (* src = "counter.v:7.3-10.6" *)
  DFF _22_ (
    .C(clk),
    .D(_00_),
    .Q(\count[0] )
  );
  (* src = "counter.v:7.3-10.6" *)
  DFF _23_ (
    .C(clk),
    .D(_01_),
    .Q(\count[1] )
  );
endmodule
